version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws s3 cp ./build s3://codefiction-stats --recursive
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
