version: 0.2

phases:
  pre_install:
    commands:
      - npm install yarn -g
  install:
    commands:
      - yarn
      - yarn bootstrap
  pre_build:
    commands:
      - yarn lint
  build:
    commands:
      - yarn build
  post_build:
    commands:
      # Deploy SPA to S3 and deploy Serverless
      - yarn deploy
artifacts:
  files:
    - "**/*"
  base-directory: "packages/stats-pages/build"
