version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm run bootstrap
  build:
    commands:
      - npm run build
      # Deploy SPA to S3 and deploy Serverless
      - npm run deploy
artifacts:
  files:
    - '**/*'
  base-directory: 'packages/stats-pages/build'
