version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm run bootstrap
  build:
    commands:
      - npm run build
      # Deploy SPA to S3
      - aws s3 cp ./packages/stats-pages/build s3://stats.codefiction.tech --recursive
      # Deploy Serverless
      - npm run deploy
artifacts:
  files:
    - '**/*'
  base-directory: 'packages/stats-pages/build'
