version: "3"

services:
  stats-api:
    ports:
      - "4000:4000"
    build:
      context: ./packages/stats-lambda/.
    command: yarn start
  stats-pages:
    ports:
      - "3000:3000"
    build:
      context: ./packages/stats-pages/.
    command: yarn start