version: 0.2

phases:
  install:
    commands:
      - npm install
      - pip install --upgrade awscli
  build:
    commands:
      - aws cloudformation package --template ./.serverless/template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml --parameters SECRET=${SECRET},YOUTUBE=${YOUTUBE},YOUTUBE_KEY=${YOUTUBE_KEY},TWITTER_CONSUMER_API_KEY=${TWITTER_CONSUMER_API_KEY},TWITTER_CONSUMER_API_SECRET_KEY=${TWITTER_CONSUMER_API_SECRET_KEY},TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN},TWITTER_ACCESS_SECRET=${TWITTER_ACCESS_SECRET},AWS_ACCESS_KEY=${AWS_ACCESS_KEY},AWS_ACCESS_SECRET_KEY=${AWS_ACCESS_SECRET_KEY}
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' ./.serverless/template-configuration.json
  post_build:
    commands:
      - cp ./.serverless/template-configuration.json ./template-configuration.json
artifacts:
  type: zip
  files:
    - template-export.yml
    - template-configuration.json
